#!/usr/bin/env python3
"""Regenerate src/data_feeders.lua from the addon's SavedVariables.

After running `/sg discover feeders` and `/reload` in-game, the captured data
lives in SeasonalGoalsDB._devFeeders inside the SavedVariables file. This script
parses that table and emits the shipped src/data_feeders.lua (NS.Sources.feeders).

Usage:
    python3 scripts/build_feeders.py [path/to/SavedVariables/SeasonalGoals.lua]

With no argument it globs the standard WSL retail path and picks the most
recently modified SeasonalGoals.lua across all account folders.
"""
import glob, os, re, sys

DEFAULT_GLOB = ("/mnt/c/Program Files (x86)/World of Warcraft/_retail_/WTF/"
                "Account/*/SavedVariables/SeasonalGoals.lua")
SLOTS = ["head", "shoulder", "chest", "wrist", "hands", "waist", "legs", "feet"]
ARMORS = ["plate", "mail", "leather", "cloth"]
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "data_feeders.lua")


def find_sv():
    if len(sys.argv) > 1:
        return sys.argv[1]
    hits = glob.glob(DEFAULT_GLOB)
    if not hits:
        sys.exit("No SavedVariables/SeasonalGoals.lua found; pass the path explicitly.")
    return max(hits, key=os.path.getmtime)


def extract_feeders_block(txt):
    """Brace-match the ["feeders"] subtable inside ["_devFeeders"]."""
    i = txt.index('["_devFeeders"]')
    j = txt.index('["feeders"]', i)
    b = txt.index('{', j)
    depth = 0
    for k in range(b, len(txt)):
        if txt[k] == '{':
            depth += 1
        elif txt[k] == '}':
            depth -= 1
            if depth == 0:
                return txt[b:k + 1]
    sys.exit("Unbalanced braces parsing _devFeeders.feeders")


def parse(block):
    """Tiny reader for the limited Lua-table shape WoW writes."""
    pos = 0

    def skipws():
        nonlocal pos
        while pos < len(block) and block[pos] in ' \t\r\n,':
            pos += 1

    def parse_table():
        nonlocal pos
        skipws()
        assert block[pos] == '{'
        pos += 1
        arr, dct = [], {}
        while True:
            skipws()
            if block[pos] == '}':
                pos += 1
                return arr if arr else dct
            if block[pos] == '[':
                m = re.match(r'\[\s*(?:"([^"]*)"|(\d+))\s*\]\s*=\s*', block[pos:])
                key = m.group(1) if m.group(1) is not None else int(m.group(2))
                pos += m.end()
                skipws()
                if block[pos] == '{':
                    dct[key] = parse_table()
                else:
                    m2 = re.match(r'("(?:[^"\\]|\\.)*"|true|false|-?\d+)', block[pos:])
                    dct[key] = m2.group(1)
                    pos += m2.end()
            else:
                arr.append(parse_table())
    return parse_table()


def emit_entry(e):
    parts = [f'source = {e.get("source", "?")}', f'itemID = {e.get("itemID", "0")}']
    if e.get("dungeon") == 'true':
        parts.append('dungeon = true')
    return "{ " + ", ".join(parts) + " }"


def main():
    sv = find_sv()
    data = parse(extract_feeders_block(open(sv, encoding='utf-8').read()))

    out = [
        "local ADDON_NAME, NS = ...",
        "",
        "-- GENERATED by scripts/build_feeders.py from `/sg discover feeders` output.",
        "-- Convertible-feeder sources from the Encounter Journal Current Season pool",
        "-- (raids + full M+ pool incl. legacy). Entry: { source, itemID, dungeon? }.",
        "-- Regenerate each season; do NOT hand-edit.",
        "NS.Sources.feeders = {",
    ]
    total = 0
    for armor in ARMORS:
        sub = data.get(armor) or {}
        out.append(f"    {armor} = {{")
        for slot in SLOTS:
            lst = sub.get(slot) if isinstance(sub, dict) else None
            if lst:
                out.append(f"        {slot} = {{")
                for e in lst:
                    out.append(f"            {emit_entry(e)},")
                    total += 1
                out.append("        },")
        out.append("    },")
    out.append("    back = {")
    for e in (data.get("back") or []):
        out.append(f"        {emit_entry(e)},")
        total += 1
    out.append("    },")
    out.append("}")
    out.append("")

    with open(OUT, "w", encoding='utf-8') as f:
        f.write("\n".join(out))
    print(f"Wrote {os.path.normpath(OUT)} with {total} feeder entries (from {sv}).")


if __name__ == "__main__":
    main()
